#!/usr/bin/env bash # configures an Nginx server so that /redirect_me is redirecting to another page
apt - get - y update
apt - get - y install nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var / www / html / index.nginx - debian.html
printf % s "server { 
listen 80; 
listen [::]:80 default_server; 
root /etc/nginx/html; 
index index.html index.htm; 
location /redirect_me { 
return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4; 
}" > /etc / nginx / sites - available / 
default service nginx start
